sudo: required
language: python

services:
  - docker

env:
  - DOCKER_IMAGE_NAME=webitel/client

before_install:
  - if [ ! -z "$TRAVIS_TAG" ]; then sed -i 's/ENV VERSION/ENV VERSION '${TRAVIS_TAG}'#'${TRAVIS_BUILD_NUMBER}'-sha1:'${TRAVIS_COMMIT}'/g' Dockerfile; else sed -i 's/ENV VERSION/ENV VERSION master#'${TRAVIS_BUILD_NUMBER}'-sha1:'${TRAVIS_COMMIT}'/g' Dockerfile; fi
  - git clone https://github.com/webitel/docs-en.git
  - pip install Sphinx

install:
  - pip install -r docs-en/requirements.txt
  - cd docs-en && pip install -r requirements.txt && make html && cd ../ && mv docs-en/build/html src/docs
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME

